### ISSUE TITLE
BUG in search in repository

### ISSUE THREAD

**Issue by dev-wouter** [ARCAD-Software/elias-vscode#91]
Hi Seb, 

we are running the latest version of the backend elias server and the latest plugin in vs-code
but the latest plugin update has a bug in the search for procedures. 
it does not recognize the type of member to open. (rpgle/sqlrpgle

![Image](https://github.com/user-attachments/assets/b2d774ce-0ce6-471c-88ac-e6e784258c5b)
![Image](https://github.com/user-attachments/assets/1a099c2e-ae86-46e8-8ca2-8e171fa4d71f)

also the literals search does some strage stuff. 

![Image](https://github.com/user-attachments/assets/d6f56476-e106-49b9-be73-750754da7aea)
![Image](https://github.com/user-attachments/assets/0d8b9671-ce51-44a4-a72f-6942a5c3b273)
for this example the source is not in system it is in gerda, so a literal search is searching over different applications?

gr wouter

**Comment by dev-wouter** [comment]
trace logging while opening a 'procedure' 

`[6/20/2025 3:14:37 PM] [TRC] Checking ARCAD-Elias REST wovaneer@eden token validity
[6/20/2025 3:14:37 PM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /checkuser  
[6/20/2025 3:14:37 PM] [TRC] REST response ARCAD-Elias REST (http) /checkuser wovaneer@eden 200 - OK: {"data":"Hello wovaneer, you're still connected to eden."}
[6/20/2025 3:14:37 PM] [TRC] Hello wovaneer, you're still connected to eden.
[6/20/2025 3:14:37 PM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /applications/SYSTEM/components/ACEXPMFS/SQLRPGLE/location {"application":"SYSTEM","name":"ACEXPMFS","type":"SQLRPGLE","version":"25.25.03"} 
[6/20/2025 3:14:37 PM] [TRC] REST response ARCAD-Elias REST (http) /applications/SYSTEM/components/ACEXPMFS/SQLRPGLE/location wovaneer@eden 200 - OK: {"data":{"file":"QRPGLESRC","library":"SYSPRDS","member":"ACEXPMFS"}}
[6/20/2025 3:14:37 PM] [TRC] Checking ARCAD-Elias REST wovaneer@eden token validity
[6/20/2025 3:14:37 PM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /checkuser  
[6/20/2025 3:14:37 PM] [TRC] REST response ARCAD-Elias REST (http) /checkuser wovaneer@eden 200 - OK: {"data":"Hello wovaneer, you're still connected to eden."}
[6/20/2025 3:14:37 PM] [TRC] Hello wovaneer, you're still connected to eden.
[6/20/2025 3:14:37 PM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /sql/select {"statement":"select FPR_CDFLG1 From AARDFPRF1 where fpr_capp = 'SYSTEM' and FPR_JNAMEL ='acsGenerateExportManifestReport' and FPR_CISDEF = 1 and FPR_CVER = '25.25.03'","metadata":false} 
[6/20/2025 3:14:38 PM] [TRC] REST response ARCAD-Elias REST (http) /sql/select wovaneer@eden 200 - OK: {"data":{"columnCount":0,"rowCount":0,"rows":[]}}`

**Comment by dev-wouter** [comment]
partial trace while searching for a literal
-> in the request there is no application mentioned 

`[6/20/2025 3:15:54 PM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /applications/SYSTEM/literals {"value":"ACS","selection":"CONTAINS","version":"25.25.03"} 
[6/20/2025 3:16:00 PM] [TRC] REST response ARCAD-Elias REST (http) /applications/SYSTEM/literals wovaneer@eden 200 - OK: {"data":[{"applicationCode":"SYSTEM","componentName":"ACMVTD2","componentObjectLibrary":"AIRBASPDNO","componentObjectType":"*FILE","componentSourceFile":"QDDSSRC","componentSourceLibrary":"AIRBASPDNS","componentType":"DSPF","versionLibrary":"SYSD240801","versionNumber":"24.08.01","length":27,"line":"    3000","typeLabel":"ALPHA","value":"       ACS Movement Details"},`

**Comment by dev-wouter** [comment]
trace while trying to open a literal search of a component not in the application 

`[6/20/2025 3:19:53 PM] [TRC] Checking ARCAD-Elias REST wovaneer@eden token validity
[6/20/2025 3:19:53 PM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /checkuser  
[6/20/2025 3:19:53 PM] [TRC] REST response ARCAD-Elias REST (http) /checkuser wovaneer@eden 200 - OK: {"data":"Hello wovaneer, you're still connected to eden."}
[6/20/2025 3:19:53 PM] [TRC] Hello wovaneer, you're still connected to eden.
[6/20/2025 3:19:53 PM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /applications/SYSTEM/components/EZAUPLDCC/SQLRPGLE/location {"application":"SYSTEM","name":"EZAUPLDCC","type":"SQLRPGLE","version":"25.25.03","fromRepository":true} 
[6/20/2025 3:19:54 PM] [ERR] 404 - Component EZAUPLDCC(SQLRPGLE) not found in SYSTEM repository for version 25.25.03: {"servlet":"com.arcadsoftware.elias.rest.server.EliasApplication","message":"Component EZAUPLDCC(SQLRPGLE) not found in SYSTEM repository for version 25.25.03","url":"/elias/arcad/v1/applications/SYSTEM/components/EZAUPLDCC/SQLRPGLE/location","status":"404"}
[6/20/2025 3:19:54 PM] [TRC] {"connection":"close","x-frame-options":"SAMEORIGIN","content-security-policy":"default-src 'self'; script-src 'self' 'unsafe-eval'","x-content-type-options":"nosniff","referrer-policy":"origin-when-cross-origin","cross-origin-resource-policy":"same-origin","cache-control":"must-revalidate,no-cache,no-store","content-type":"application/json","content-length":"263","server":"Jetty(9.4.54.v20240208)"}`

**Comment by sebjulliand** [comment]
Fixed in version `2.4.2`.

**Comment by dev-wouter** [comment]
the procedure part is working for the literals i still have the same issue

opening the source in the literal list that is in application GERDA while searching in application SYSTEM 

![Image](https://github.com/user-attachments/assets/2323559f-6574-4c6b-9dc2-cbd1132153cf)

**Comment by sebjulliand** [comment]
@dev-wouter could you send me the traces after the literals have been listed? I need to check what's returned. Thanks.

**Comment by dev-wouter** [comment]
sure, 

this is a part of the 'search' 
`6/24/2025 7:07:26 AM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /applications/SYSTEM/literals {"value":"acs","selection":"CONTAINS","version":"25.25.03"} 
[6/24/2025 7:07:29 AM] [TRC] REST response ARCAD-Elias REST (http) /applications/SYSTEM/literals wovaneer@eden 200 - OK: {"data":[{"applicationCode":"SYSTEM","componentName":"ACMVTD2","componentObjectLibrary":"AIRBASPDNO","componentObjectType":"*FILE","componentSourceFile":"QDDSSRC","componentSourceLibrary":"AIRBASPDNS","componentType":"DSPF","versionLibrary":"SYSD240801","versionNumber":"24.08.01","length":27,"line":"    3000","typeLabel":"ALPHA","value":"       ACS Movement Details"},`


and this is when the error pop-up
`[6/24/2025 7:08:28 AM] [TRC] REST request ARCAD-Elias REST (http) wovaneer@eden: get /applications/GERDA/components/EZAUPLDCC/SQLRPGLE/location {"application":"GERDA","name":"EZAUPLDCC","type":"SQLRPGLE","version":"25.25.03"} 
[6/24/2025 7:08:28 AM] [ERR] 500 - Fatal error: com.quadra.services.dao.QuadraDAOException: 	[MSG0863] [30] Object/member EZAUPLDCC of type SQLRPGLE has not been modified in environment GERDA//25.25.03.: "com.arcadsoftware.redux.core.daos.ComponentDAO.getLocalizedSource(ComponentDAO.java:166); com.arcadsoftware.elias.rest.server.arcad.resource.ComponentsResource.getComponentLocation(ComponentsResource.java:565); sun.reflect.GeneratedMethodAccessor257.invoke(Unknown Source); sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55); java.lang.reflect.Method.invoke(Method.java:508)"
[6/24/2025 7:08:28 AM] [TRC] {"connection":"close","content-type":"application/json","x-frame-options":"SAMEORIGIN","content-security-policy":"default-src 'self'; script-src 'self' 'unsafe-eval'","x-content-type-options":"nosniff","referrer-policy":"origin-when-cross-origin","cross-origin-resource-policy":"same-origin","content-length":"409","server":"Jetty(9.4.54.v20240208)"}`

**Comment by sebjulliand** [comment]
Ok, I think I see the problem. @dev-wouter can you confirm that since the last update the target application is correct (i.e. `EZAUPLDCC` is in application `GERDA`, as stated by the error), but the version is not (it should be `24.08.01` instead of `25.25.03` which probably doesn't exist in `GERDA`).

**Comment by dev-wouter** [comment]
it could be that 25.25.03 is not existing in gerda.
as these 'applications' are being worked on by different persons. for me it would be enough as literals would search in its own application .

![Image](https://github.com/user-attachments/assets/9be6f5fd-ea24-43a4-9fdd-63b98afb47c0)

**Comment by sebjulliand** [comment]
Hi @dev-wouter ,
before I make a new release, would you mind downloading this snapshot and install it, to check if your issue is fixed for good? Thanks!

[arcad-elias-2.4.3-SNAPSHOT.vsix.zip](https://github.com/user-attachments/files/20928558/arcad-elias-2.4.3-SNAPSHOT.vsix.zip)

**Comment by dev-wouter** [comment]
sure, will test it today

**Comment by dev-wouter** [comment]
if i now search for the literal 'ACS' in application 'system' i still get literals from aplication 'gerda' but they open now. 

![Image](https://github.com/user-attachments/assets/05f060d1-0c18-48e5-a2e0-92d4bfc98ed2)

**Comment by sebjulliand** [comment]
I won't remove inter-application links - adding a setting to disable them, maybe later.
I'll fix another issue reported yesterday and proceed with the new release, hopefully today 😊

**Comment by dev-wouter** [comment]
works fine with me.

**Comment by sebjulliand** [comment]
Version 2.4.3 is now out to fix this 😊
